---
abstract: 'Make it easy to migrate DBIC based databases'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  File::Path: 0
  File::Spec::Functions: 0
  Test::Most: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300008, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Migration
requires:
  Class::Load: 0
  DBD::Sqlite: 0
  DBIx::Class::DeploymentHandler: 0.001008
  DBIx::Class::Fixtures: 1.001014
  DBIx::Class::Schema::Loader: 0.07017
  Devel::PartialDump: 0
  File::Copy: 0
  File::Path: 0
  File::ShareDir::ProjectDistDir: 0
  File::Spec: 0
  File::Temp: 0
  JSON::XS: 0
  Moose: 0
  MooseX::Attribute::ENV: 0
  MooseX::Getopt: 0
  MooseX::Traits::Pluggable: 0
  MooseX::Types::LoadableClass: 0
version: 0.003
